"""
语音克隆示例 - 参照音频克隆音色，支持风格控制
Voice Cloning Example - Clone voice with style control
"""

from voxcpmm_wrap import VoxCPMWrap
import soundfile as sf

model = VoxCPMWrap.from_pretrained("openbmb/VoxCPM2", device="auto")

# === 1. 基础克隆（直接克隆音色）===
# 只需提供参考音频，VoxCPM2 会克隆其音色
wav = model.generate(
    text="This is a cloned voice generated by VoxCPM2.",
    reference_wav_path="path/to/your_reference_voice.wav",  # 替换为你的参考音频
)
sf.write("clone_basic.wav", wav, model.sample_rate)
print("✅ 基础克隆完成: clone_basic.wav")

# === 2. 可控克隆（带风格描述）===
# 在文本开头添加风格描述，保持克隆音色的同时调整表达
wav = model.generate(
    text="(slightly faster, cheerful tone)This is a cloned voice with style control.",
    reference_wav_path="path/to/your_reference_voice.wav",
    cfg_value=2.5,
    inference_timesteps=10,
)
sf.write("clone_controllable.wav", wav, model.sample_rate)
print("✅ 可控克隆完成: clone_controllable.wav")

# === 3. 极致克隆（音频 + 转写文本）===
# 同时提供参考音频和转写文本，实现逐音素级完美克隆
wav = model.generate(
    text="This is an ultra cloning demonstration using VoxCPM2.",
    prompt_wav_path="path/to/your_reference_voice.wav",   # 参考音频
    prompt_text="The transcript of the reference audio.",  # 转写文本
    reference_wav_path="path/to/your_reference_voice.wav",  # 可选，增强相似度
)
sf.write("clone_ultra.wav", wav, model.sample_rate)
print("✅ 极致克隆完成: clone_ultra.wav")

print("\n🎙️ 三种克隆模式完成！")
model.unload()